In [1]:
import pandas as pd

In [2]:
f1 = 'lsa-comp-dem2180.csv'
f2 = 'lsa-comp-meuse.csv'

In [5]:
df1 = pd.read_csv(f1, index_col=False)
df1.drop(columns=['Unnamed: 0'], inplace=True)
df1.head()

       rmse  time-linalgsolve  rmse_lsa  time-lsa  nn  dataset
0  4.542369          0.024086  4.542369  0.030443   4  dem2180
1  4.518797          0.023378  4.518797  0.031923   8  dem2180
2  5.163855          0.024277  5.163855  0.033809  16  dem2180
3  5.259920          0.028030  5.259920  0.043930  32  dem2180
4  4.847665          0.032389  4.847665  0.086493  64  dem2180

In [6]:
df2 = pd.read_csv(f2, index_col=False)
df2.drop(columns=['Unnamed: 0'], inplace=True)
df2.head()

       rmse  time-linalgsolve  rmse_lsa  time-lsa  nn dataset
0  0.747242          0.018661  0.747242  0.022680   4   meuse
1  0.585143          0.019339  0.585143  0.029146   8   meuse
2  0.655050          0.016812  0.655050  0.024158  16   meuse
3  0.687484          0.018080  0.687484  0.025354  32   meuse
4  0.630097          0.016673  0.630097  0.027855  64   meuse

In [10]:
df = pd.concat([df1, df2], axis=0)

In [11]:
len(df) == (len(df1) + len(df2))

True

In [12]:
df.head()

       rmse  time-linalgsolve  rmse_lsa  time-lsa  nn  dataset
0  4.542369          0.024086  4.542369  0.030443   4  dem2180
1  4.518797          0.023378  4.518797  0.031923   8  dem2180
2  5.163855          0.024277  5.163855  0.033809  16  dem2180
3  5.259920          0.028030  5.259920  0.043930  32  dem2180
4  4.847665          0.032389  4.847665  0.086493  64  dem2180

In [13]:
# average RMSE per nn

In [15]:
avg_rmse_nn = df.groupby('nn')[['rmse', 'rmse_lsa']].mean()

In [17]:
avg_rmse_nn['rmse'] - avg_rmse_nn['rmse_lsa']

nn
4     -4.440892e-16
8      0.000000e+00
16     0.000000e+00
32    -8.881784e-16
64    -3.552714e-15
128    2.341096e-10
256   -7.472416e-06
512    5.260083e-07
dtype: float64

In [18]:
# average time per nn

In [19]:
avg_time_nn = df.groupby('nn')[['time-linalgsolve', 'time-lsa']].mean()

In [21]:
avg_time_nn['time-linalgsolve'] - avg_time_nn['time-lsa']

nn
4     -0.006057
8     -0.006906
16    -0.009496
32    -0.013793
64    -0.034989
128   -0.214857
256   -0.763580
512   -3.212537
dtype: float64

In [ ]:
# the only difference seems to be in computation times